# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CityWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for CityWeather
	pod 'Alamofire', '~> 5.1'

  target 'CityWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CityWeatherUITests' do
    # Pods for testing
  end

end
